apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

# Placeholders para serem substituídos pelo ConfigMap
images:
- name: auth-service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/auth-service
  newTag: ${IMAGE_TAG}
- name: flag-service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/flag-service
  newTag: ${IMAGE_TAG}
- name: targeting-service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/targeting-service
  newTag: ${IMAGE_TAG}
- name: evaluation-service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/evaluation-service
  newTag: ${IMAGE_TAG}
- name: analytics-service
  newName: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/analytics-service
  newTag: ${IMAGE_TAG}

# Substitui placeholders pelos valores do ConfigMap
replacements:
- source:
    kind: ConfigMap
    name: aws-config
    namespace: togglemaster
    fieldPath: data.AWS_ACCOUNT_ID
  targets:
  - select:
      kind: Kustomization
      name: .*
    fieldPaths:
    - images.[name=auth-service].newName
    - images.[name=flag-service].newName
    - images.[name=targeting-service].newName
    - images.[name=evaluation-service].newName
    - images.[name=analytics-service].newName
    options:
      create: true
- source:
    kind: ConfigMap
    name: aws-config
    namespace: togglemaster
    fieldPath: data.AWS_REGION
  targets:
  - select:
      kind: Kustomization
    fieldPaths:
    - images.[name=auth-service].newName
    - images.[name=flag-service].newName
    - images.[name=targeting-service].newName
    - images.[name=evaluation-service].newName
    - images.[name=analytics-service].newName
    options:
      create: true
- source:
    kind: ConfigMap
    name: aws-config
    namespace: togglemaster
    fieldPath: data.IMAGE_TAG
  targets:
  - select:
      kind: Kustomization
    fieldPaths:
    - images.[name=auth-service].newTag
    - images.[name=flag-service].newTag
    - images.[name=targeting-service].newTag
    - images.[name=evaluation-service].newTag
    - images.[name=analytics-service].newTag
    options:
      create: true

# Customizações específicas de produção

patches:
  - target:
      kind: Deployment
      name: auth-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2