apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

# Customizações específicas de produção




patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: auth-service
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: flag-service
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: targeting-service
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: evaluation-service
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: analytics-service

# Imagens com registry ECR e tag latest
images:
- name: analytics-service
  newName: 480176645265.dkr.ecr.us-east-1.amazonaws.com/analytics-service
  newTag: 2906f2d2011b1c276c9bbf06a36541c27142bf22
- name: auth-service
  newName: 480176645265.dkr.ecr.us-east-1.amazonaws.com/auth-service
  newTag: 0363c68c0e290b346453bc7a5755fd8b41d3e92a
- name: evaluation-service
  newName: 480176645265.dkr.ecr.us-east-1.amazonaws.com/evaluation-service
  newTag: 25268e58ee9562d88c07a4dc46136a61ec2c7627
- name: flag-service
  newName: 480176645265.dkr.ecr.us-east-1.amazonaws.com/flag-service
  newTag: 38b1c8fce20f5550e115029f75512549a6535bc3
- name: targeting-service
  newName: 480176645265.dkr.ecr.us-east-1.amazonaws.com/targeting-service
  newTag: c2c5e3287ff30f52fa72ed6d21957b4dabf9eb27
