apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- hpa.yaml
images:
- name: evaluation-service
  newName: /evaluation-service
  newTag: 3f47f8ab82754e65af1468a5b802b9c520b7314f
