apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- hpa.yaml
images:
- name: evaluation-service
  newName: /evaluation-service
  newTag: 0e5eada7075e99cf25b8bbc553c9288186171390
