apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- hpa.yaml
images:
- name: evaluation-service
  newName: /evaluation-service
  newTag: b5ef771f3d272f3958f842b55f5de1b74a050b6f
