apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: togglemaster-secrets
  namespace: togglemaster
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: togglemaster-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: togglemaster/prod/auth-credentials
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: togglemaster/prod/auth-credentials
        property: password
    - secretKey: MASTER_KEY
      remoteRef:
        key: togglemaster/prod/master-credentials
        property: password
    - secretKey: SERVICE_API_KEY
      remoteRef:
        key: togglemaster/prod/api-key-credentials
        property: password