apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: togglemaster-secrets
  namespace: togglemaster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm-parameter-store
    kind: ClusterSecretStore
  target:
    name: db-credentials   
    creationPolicy: Owner
  data:
    - secretKey: AUTH_DB_USERNAME
      remoteRef:
        key: /togglemaster/prod/auth/credentials
        property: username  
    - secretKey: AUTH_DB_PASSWORD
      remoteRef:
        key: /togglemaster/prod/auth/credentials
        property: password
    - secretKey: FLAG_DB_USERNAME
      remoteRef:
        key: /togglemaster/prod/flag/credentials
        property: username
    - secretKey: FLAG_DB_PASSWORD
      remoteRef:
        key: /togglemaster/prod/flag/credentials
        property: password
    - secretKey: TARGETING_DB_USERNAME
      remoteRef:
        key: /togglemaster/prod/targeting/credentials
        property: username
    - secretKey: TARGETING_DB_PASSWORD
      remoteRef:
        key: /togglemaster/prod/targeting/credentials
        property: password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: /togglemaster/prod/redis/credentials
        property: password