apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: targeting-service
  newName: /targeting-service
  newTag: 0e5eada7075e99cf25b8bbc553c9288186171390
