apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- hpa.yaml
images:
- name: analytics-service
  newName: /analytics-service
  newTag: 4adefe7c9dbff363b339603cee9ca9f6c64c50e9
