apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- hpa.yaml
images:
- name: analytics-service
  newName: /analytics-service
  newTag: 5dc3a808a7688af2e9b96cd226c5672a13b680fa
