apiVersion: batch/v1
kind: Job
metadata:
  name: targeting-db-init
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: postgres-init
        image: postgres:15
        command:
          - /bin/sh
          - -c
        args:
          - |
            export PGPASSWORD=$POSTGRES_PASSWORD
            psql -h $RDS_TARGETING_ENDPOINT -U $POSTGRES_USER -d postgres -c "CREATE DATABASE targeting_db;"
            psql -h $RDS_TARGETING_ENDPOINT -U $POSTGRES_USER -d targeting_db -f /sql/init.sql

        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-targeting-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-targeting-secret
              key: password
        - name: RDS_TARGETING_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: togglemaster-config
              key: RDS_TARGETING_ENDPOINT
        volumeMounts:
        - name: sql
          mountPath: /sql
      volumes:
      - name: sql
        configMap:
          name: targeting-init-sql