apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: flag-service
  newName: 480176645265.dkr.ecr.us-east-1.amazonaws.com/flag-service
  newTag: a907d86d6f5715d86e4ba6759f774296217ec32d
