apiVersion: v1
kind: ConfigMap
metadata:
  name: togglemaster-config
  namespace: togglemaster
data:
  AWS_REGION: "${AWS_REGION}"
  AWS_SQS_URL: "https://sqs.${AWS_REGION}.amazonaws.com/${AWS_ACCOUNT_ID}/togglemaster-evaluation-events"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
  RDS_AUTH_ENDPOINT: "${RDS_AUTH_ENDPOINT}"
  RDS_FLAG_ENDPOINT: "${RDS_FLAG_ENDPOINT}"
  RDS_TARGETING_ENDPOINT: "${RDS_TARGETING_ENDPOINT}"
  REDIS_ENDPOINT: "${REDIS_ENDPOINT}"